spring.application.name=customer-service
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/customer-service
spring.datasource.username=root
spring.datasource.password=Naseeruddin@786
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:29092
